export const MatchActionType = {
    DATA_LOADED:"DATA_LOADED",
    SET_UP_COMMING_ALL_MATCHES: "SET_UP_COMMING_ALL_MATCHES",
    SET_All_BEST_MATCHES: "SET_All_BEST_MATCHES",
    SET_MATCH_HISTORY: "SET_MATCH_HISTORY",
    SET_CLUBS: "SET_CLUBS",
};