export const MatchActionType = {
    DATA_LOADED:"DATA_LOADED",
    SET_UP_COMMING_ALL_MATCHES: "SET_UP_COMMING_ALL_MATCHES",
    SET_UP_All_BEST_MATCHES: "SET_UP_All_BEST_MATCHES",
    SET_UP_MATCH_HISTORY: "SET_UP_MATCH_HISTORY",
};